repos:
  - repo: local
    hooks:
      - id: system
        name: Safety
        entry: poetry run safety check
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black app
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort app
        pass_filenames: false
        language: system
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.770'
    hooks:
      - id: mypy
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]
  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: poetry run pytest
        language: system
        types: [python]
        pass_filenames: false
