"""empty message

Revision ID: 85bda85aeecc
Revises: 2c5d45cff580
Create Date: 2021-09-07 21:58:55.324142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '85bda85aeecc'
down_revision = '2c5d45cff580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_database',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('row_id', sa.BigInteger(), nullable=True),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('date_hour', sa.DateTime(), nullable=True),
    sa.Column('row', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_request',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('item', sa.Column('modified_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'modified_by')
    op.drop_table('audit_request')
    op.drop_table('audit_database')
    # ### end Alembic commands ###
