"""empty message

Revision ID: e5cb8f2287a1
Revises: 85bda85aeecc
Create Date: 2021-09-10 18:59:42.305855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5cb8f2287a1'
down_revision = '85bda85aeecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_auth',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('date_hour', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_auth')
    # ### end Alembic commands ###
